import axios from "axios";
import { ChevronLeft, ChevronRight, Expand, FilePlus2, Grip, LoaderCircle, MoreHorizontal, Pencil, Minus, Plus, Send, Sparkles, Trash2 } from "lucide-react";
import { useContext, useEffect, useId, useRef, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CanvasDataContext } from "./CanvasWrapper";

type CanvasMap = { _id: string; title: string; topic: string; subject: string; grade: string; schoolType: string; content: string; mermaidCode: string; updatedAt: string };
const extractMermaidCode = (response: string) => response.match(/```mermaid\s*([\s\S]*?)```/i)?.[1]?.trim() || response.trim();
const normalizeMermaidCode = (response: string) => {
  const code = extractMermaidCode(response).replace(/\r/g, ""); const graphStart = code.search(/^\s*(?:graph|flowchart)\s+(?:TD|LR)\b/im);
  return graphStart >= 0 ? code.slice(graphStart).split("\n").filter((line) => !/^\s*(?:#|```|classDef\b|class\b|style\b|click\b|linkStyle\b|subgraph\b|end\b)/i.test(line)).join("\n").trim() : code;
};
const SUBJECTS = ["Informatika", "Matematika", "Srpski jezik", "Engleski jezik", "Istorija", "Geografija", "Biologija", "Hemija", "Fizika", "Svet oko nas", "Drugo"];
const SCHOOL_TYPES = ["Osnovna škola", "Gimnazija", "Srednja stručna škola"];
const GRADES_BY_SCHOOL: Record<string, string[]> = {
  "Osnovna škola": ["V razred", "VI razred", "VII razred", "VIII razred"],
  Gimnazija: ["I razred", "II razred", "III razred", "IV razred"],
  "Srednja stručna škola": ["I razred", "II razred", "III razred", "IV razred"],
};

const MermaidViewport = ({ code }: { code: string }) => {
  const id = useId().replace(/:/g, "-"); const [svg, setSvg] = useState(""); const [error, setError] = useState("");
  const [scale, setScale] = useState(1); const [position, setPosition] = useState({ x: 0, y: 0 }); const [selected, setSelected] = useState("");
  const drag = useRef<{ x: number; y: number; originX: number; originY: number } | null>(null);
  useEffect(() => { let cancelled = false; setSvg(""); setError(""); void import("mermaid").then(({ default: mermaid }) => { mermaid.initialize({ startOnLoad: false, securityLevel: "strict", theme: "neutral", flowchart: { htmlLabels: false, useMaxWidth: false, curve: "basis" } }); return mermaid.render(`canvas-map-${id}`, normalizeMermaidCode(code)); }).then(({ svg }) => !cancelled && setSvg(svg)).catch(() => !cancelled && setError("Generisana mapa ima nevažeću Mermaid sintaksu. Otvorite kod, ispravite ga ili generišite novu mapu.")); return () => { cancelled = true; }; }, [code, id]);
  const zoom = (delta: number) => setScale((value) => Math.min(2.5, Math.max(0.35, Number((value + delta).toFixed(2)))));
  if (error) return <div className="flex h-full min-h-[560px] flex-col items-center justify-center gap-4 p-8 text-center"><p className="max-w-md font-medium text-destructive">{error}</p><p className="max-w-md text-sm text-slate-500">Mapa nije dostupna za prikaz. Generišite novu mapu iz ispravljenog nastavnog konteksta.</p></div>;
  return <div className="relative h-full min-h-[560px] overflow-hidden rounded-xl border border-slate-200 bg-[radial-gradient(#cbd5e1_1px,transparent_1px)] bg-size-[18px_18px] dark:border-slate-800 dark:bg-slate-950" onWheel={(event) => { event.preventDefault(); zoom(event.deltaY < 0 ? .1 : -.1); }} onPointerMove={(event) => { if (!drag.current) return; setPosition({ x: drag.current.originX + event.clientX - drag.current.x, y: drag.current.originY + event.clientY - drag.current.y }); }} onPointerUp={() => { drag.current = null; }}>
    <div className="absolute left-3 top-3 z-10 flex items-center gap-1 rounded-lg border bg-white/90 p-1 shadow-sm dark:bg-slate-900/90"><Button size="icon" variant="ghost" onClick={() => zoom(.15)} aria-label="Uvećaj"><Plus className="h-4 w-4" /></Button><span className="w-11 text-center text-xs font-semibold">{Math.round(scale * 100)}%</span><Button size="icon" variant="ghost" onClick={() => zoom(-.15)} aria-label="Umanji"><Minus className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => { setScale(1); setPosition({ x: 0, y: 0 }); }} aria-label="Resetuj prikaz"><Expand className="h-4 w-4" /></Button></div>
    {selected && <div className="absolute right-3 top-3 z-10 max-w-48 rounded-lg bg-primary px-3 py-2 text-xs font-medium text-primary-foreground shadow">Izabrani čvor: {selected}</div>}
    {!svg ? <div className="flex h-full min-h-[560px] items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-primary" /></div> : <div className="flex h-full min-h-[560px] min-w-max items-center justify-center touch-none cursor-grab active:cursor-grabbing" style={{ transform: `translate(${position.x}px, ${position.y}px) scale(${scale})`, transformOrigin: "center", transition: drag.current ? "none" : "transform 120ms ease-out" }} onPointerDown={(event) => { drag.current = { x: event.clientX, y: event.clientY, originX: position.x, originY: position.y }; event.currentTarget.setPointerCapture(event.pointerId); }} onClick={(event) => { const node = (event.target as Element).closest("g.node"); const label = node?.textContent?.replace(/\s+/g, " ").trim(); if (label) setSelected(label); }} dangerouslySetInnerHTML={{ __html: svg }} />}
    <div className="absolute bottom-3 left-3 flex items-center gap-2 rounded-lg bg-slate-900/80 px-3 py-2 text-xs text-white"><Grip className="h-3.5 w-3.5" />Prevucite za pomeranje · točkić za zum · kliknite čvor za detalj</div>
  </div>;
};

const CanvasPage = () => {
  const canvas = useContext(CanvasDataContext); const [predmet, setPredmet] = useState("Informatika"); const [razred, setRazred] = useState(""); const [vrstaSkole, setVrstaSkole] = useState(""); const [tema, setTema] = useState("");
  const [map, setMap] = useState<CanvasMap | null>(null); const [isLoading, setIsLoading] = useState(false); const [historyOpen, setHistoryOpen] = useState(true); const [renameTarget, setRenameTarget] = useState<CanvasMap | null>(null); const [newTitle, setNewTitle] = useState(""); const [isRenaming, setIsRenaming] = useState(false);
  const generate = async () => { if (![predmet, razred, vrstaSkole, tema].every((value) => value.trim())) return toast.error("Popunite predmet, razred, vrstu škole i temu."); setIsLoading(true); try { const response = await axios.post(`${import.meta.env.VITE_BACKEND}/api/canvas/generate`, { predmet, razred, vrstaSkole, tema }, { withCredentials: true }); setMap(response.data.map); canvas?.setBalance(response.data.newBalance); await Promise.all([canvas?.refreshMaps(), canvas?.refreshBalance()]); toast.success(`Mapa je sačuvana. Potrošeno: ${response.data.cost} kredita.`); } catch (error: any) { const data = error.response?.data; if (typeof data?.newBalance === "number") canvas?.setBalance(data.newBalance); toast.error(data?.message || "Došlo je do greške prilikom generisanja mape."); } finally { setIsLoading(false); } };
  const openMap = async (id: string) => { try { const response = await axios.get(`${import.meta.env.VITE_BACKEND}/api/canvas/maps/${id}`, { withCredentials: true }); const saved = response.data.map as CanvasMap; setMap(saved); setPredmet(saved.subject); setRazred(saved.grade); setVrstaSkole(saved.schoolType); setTema(saved.topic); } catch { toast.error("Mapu nije moguće učitati."); } };
  const removeMap = async (id: string) => { try { await axios.delete(`${import.meta.env.VITE_BACKEND}/api/canvas/maps/${id}`, { withCredentials: true }); if (map?._id === id) setMap(null); await canvas?.refreshMaps(); toast.success("Mapa je obrisana."); } catch { toast.error("Mapu nije moguće obrisati."); } };
  const newMap = () => { setMap(null); setTema(""); };
  const schoolChanged = (value: string) => { setVrstaSkole(value); setRazred(""); };
  const renameMap = async () => { if (!renameTarget || !newTitle.trim()) return; setIsRenaming(true); try { const response = await axios.patch(`${import.meta.env.VITE_BACKEND}/api/canvas/maps/${renameTarget._id}`, { title: newTitle.trim() }, { withCredentials: true }); if (map?._id === renameTarget._id) setMap(response.data.map); await canvas?.refreshMaps(); setRenameTarget(null); toast.success("Mapa je preimenovana."); } catch (error: any) { toast.error(error.response?.data?.message || "Mapu nije moguće preimenovati."); } finally { setIsRenaming(false); } };
  return <section className="mx-auto flex max-w-[1600px] flex-col gap-5 py-6 lg:flex-row"><aside className={`${historyOpen ? "w-full lg:w-72" : "w-11"} shrink-0 overflow-hidden rounded-2xl border border-slate-200 bg-white transition-all dark:border-slate-800 dark:bg-slate-900`}><div className="flex items-center justify-between border-b p-3"><span className={historyOpen ? "text-sm font-bold" : "hidden"}>Sačuvane mape</span><Button size="icon" variant="ghost" onClick={() => setHistoryOpen(!historyOpen)}>{historyOpen ? <ChevronLeft className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</Button></div>{historyOpen && <div className="grid gap-1 p-2 sm:grid-cols-2 lg:block lg:space-y-1"><Button className="mb-2 w-full justify-start sm:col-span-2 lg:mb-2" onClick={newMap}><FilePlus2 className="mr-2 h-4 w-4" />Nova mapa</Button>{canvas?.maps.length ? canvas.maps.map((item) => <div key={item._id} role="button" tabIndex={0} onClick={() => openMap(item._id)} onKeyDown={(event) => event.key === "Enter" && openMap(item._id)} className={`group w-full cursor-pointer rounded-xl p-3 text-left hover:bg-slate-100 dark:hover:bg-slate-800 ${map?._id === item._id ? "bg-primary/10" : ""}`}><div className="flex items-start justify-between gap-2"><span className="line-clamp-2 text-sm font-semibold">{item.title}</span><DropdownMenu><DropdownMenuTrigger asChild><span onClick={(event) => event.stopPropagation()}><Button size="icon" variant="ghost" className="h-7 w-7 opacity-100 lg:opacity-0 lg:group-hover:opacity-100" aria-label="Opcije mape"><MoreHorizontal className="h-4 w-4" /></Button></span></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => { setRenameTarget(item as CanvasMap); setNewTitle(item.title); }}><Pencil className="mr-2 h-4 w-4" />Preimenuj</DropdownMenuItem><DropdownMenuItem variant="destructive" onSelect={() => removeMap(item._id)}><Trash2 className="mr-2 h-4 w-4" />Obriši</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><span className="mt-1 block text-xs text-slate-500">{item.subject} · {item.grade}</span><span className="mt-1 block text-[11px] text-slate-400">{new Date(item.updatedAt).toLocaleDateString("sr-RS")}</span></div>) : <p className="p-4 text-center text-sm text-slate-500">Još nemate sačuvanih mapa.</p>}</div>}</aside>
    <div className="min-w-0 flex-1 space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-bold">Novi Canvas zahtev</p><p className="text-xs text-slate-500">Kontekst određuje pedagoški nivo i strukturu mape.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{canvas?.cost ?? 10} Canvas kredita</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_2fr_auto]"><label className="grid gap-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300">Predmet<Select value={predmet} onValueChange={setPredmet} disabled={isLoading}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{SUBJECTS.map((subject) => <SelectItem key={subject} value={subject}>{subject}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300">Tip škole<Select value={vrstaSkole} onValueChange={schoolChanged} disabled={isLoading}><SelectTrigger className="w-full"><SelectValue placeholder="Izaberite tip" /></SelectTrigger><SelectContent>{SCHOOL_TYPES.map((type) => <SelectItem key={type} value={type}>{type}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300">Razred<Select value={razred} onValueChange={setRazred} disabled={isLoading || !vrstaSkole}><SelectTrigger className="w-full"><SelectValue placeholder={vrstaSkole ? "Izaberite razred" : "Prvo izaberite školu"} /></SelectTrigger><SelectContent>{(GRADES_BY_SCHOOL[vrstaSkole] || []).map((grade) => <SelectItem key={grade} value={grade}>{grade}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300">Tema lekcije<Input value={tema} onChange={(e) => setTema(e.target.value)} placeholder="npr. Fotosinteza" disabled={isLoading} /></label><Button className="self-end" onClick={generate} disabled={isLoading}>{isLoading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <><Send className="mr-2 h-4 w-4" />Generiši</>}</Button></div></div>
      <div className="flex items-center justify-between"><h2 className="text-xl font-bold">{map?.title || "Canvas radni prostor"}</h2></div>
      <div className="min-h-[620px] rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">{isLoading ? <div className="flex h-[560px] flex-col items-center justify-center gap-4 text-center"><LoaderCircle className="h-11 w-11 animate-spin text-primary" /><div><p className="font-semibold">IskraAI projektuje mapu uma…</p><p className="mt-1 text-sm text-slate-500">Malo složenije mape mogu trajati nekoliko sekundi.</p></div></div> : map ? <MermaidViewport code={map.mermaidCode || extractMermaidCode(map.content)} /> : <div className="flex h-[560px] flex-col items-center justify-center text-center"><span className="mb-4 rounded-2xl bg-primary/10 p-4 text-primary"><Sparkles className="h-9 w-9" /></span><h3 className="font-bold">Započnite novu mapu uma</h3><p className="mt-2 max-w-sm text-sm text-slate-500">Unesite kontekst lekcije iznad. Vaša mapa se automatski čuva u Canvas biblioteci.</p></div>}</div></div><Dialog open={Boolean(renameTarget)} onOpenChange={(open) => !open && setRenameTarget(null)}><DialogContent><DialogHeader><DialogTitle>Preimenuj mapu</DialogTitle><DialogDescription>Izaberite jasan naziv po kojem ćete lako pronaći ovu mapu.</DialogDescription></DialogHeader><Input autoFocus value={newTitle} onChange={(event) => setNewTitle(event.target.value)} onKeyDown={(event) => event.key === "Enter" && renameMap()} placeholder="Naziv mape" /><DialogFooter><Button variant="outline" onClick={() => setRenameTarget(null)}>Odustani</Button><Button onClick={renameMap} disabled={!newTitle.trim() || isRenaming}>{isRenaming ? "Čuvanje…" : "Sačuvaj naziv"}</Button></DialogFooter></DialogContent></Dialog></section>;
};
export default CanvasPage;
